export const ADD_SUPPLIER = 'ADD_SUPPLIER';
export const ADD_SUPPLIER_SUCCESS = 'ADD_SUPPLIER_SUCCESS';
export const ADD_SUPPLIER_ERROR = 'ADD_SUPPLIER_ERROR';

export const EDIT_SUPPLIER = 'EDIT_SUPPLIER';
export const EDIT_SUPPLIER_SUCCESS = 'EDIT_SUPPLIER_SUCCESS';
export const EDIT_SUPPLIER_ERROR = 'EDIT_SUPPLIER_ERROR';

export const DELETE_SUPPLIER = 'DELETE_SUPPLIER';
export const DELETE_SUPPLIER_SUCCESS = 'DELETE_SUPPLIER_SUCCESS';
export const DELETE_SUPPLIER_ERROR = 'DELETE_SUPPLIER_ERROR';

export const GET_SUPPLIER = 'GET_SUPPLIER';
export const GET_SUPPLIER_SUCCESS = 'GET_SUPPLIER_SUCCESS';
export const GET_SUPPLIER_ERROR = 'GET_SUPPLIER_ERROR';

export const GET_SUPPLIERS = 'GET_SUPPLIERS';
export const GET_SUPPLIERS_SUCCESS = 'GET_SUPPLIERS_SUCCESS';
export const GET_SUPPLIERS_ERROR = 'GET_SUPPLIERS_ERROR';

export const SET_SUPPLIER = 'SET_SUPPLIER';